version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "project-bohr"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19nncj162p3yy"
s3_prefix = "project-bohr"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
