AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  project-bohr

  Sample SAM Template for project-bohr

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: python3.8
Resources:
  CreateMenuFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/menu
      Handler: create.handler
      Architectures:
        - x86_64
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Select [1, !Split ["/", !GetAtt MenuTable.Arn]]
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/v1/merchant/{merchantId}/menu
            Method: post
  ListMenuFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/menu
      Handler: list.handler
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/v1/merchant/{merchantId}/menu
            Method: get
  MenuTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: bohr-menu
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
